# -*- coding: utf-8 -*-
"""predictive_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fsfi_N8EmvVQmP9FHQ1ov85GiMLkFO6W
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

train = pd.read_csv("train.csv")
stores = pd.read_csv("stores.csv")
oil = pd.read_csv("oil.csv")
holidays = pd.read_csv("holidays_events.csv")
transactions = pd.read_csv("transactions.csv")

train.head()

train.shape

train.info()

train.describe()

train.isnull().sum()

train.duplicated().sum()

train['date'] = pd.to_datetime(train['date'])

train.info()

train['year'] = train['date'].dt.year
train['month'] = train['date'].dt.month
train['day'] = train['date'].dt.day
train['dayofweek'] = train['date'].dt.dayofweek

train.head()

daily_sales = train.groupby('date')['sales'].sum()

plt.figure(figsize=(15,5))

daily_sales.plot()

plt.title("Daily Sales Trend")
plt.xlabel("Date")
plt.ylabel("Sales")

plt.show()

monthly_sales = train.groupby('month')['sales'].sum()

monthly_sales.plot(kind='bar')

plt.title("Monthly Sales")

plt.show()

top_family = train.groupby('family')['sales'].sum().sort_values(ascending=False).head(10)

top_family.plot(kind='bar')

plt.title("Top Product Families")

plt.show()

train = train.merge(
    stores,
    on='store_nbr',
    how='left'
)

train.head()

train.shape

oil['date'] = pd.to_datetime(oil['date'])

train = train.merge(
    oil,
    on='date',
    how='left'
)

train.head()

train.isnull().sum()

train['dcoilwtico'] = train['dcoilwtico'].fillna(
    train['dcoilwtico'].median()
)

holidays['date'] = pd.to_datetime(
    holidays['date']
)

holiday_dates = set(
    holidays['date']
)

train['is_holiday'] = train['date'].isin(
    holiday_dates
).astype(int)

train[['date','is_holiday']].head()

features = [
    'store_nbr',
    'onpromotion',
    'year',
    'month',
    'day',
    'dayofweek',
    'is_holiday',
    'dcoilwtico'
]

target = 'sales'

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

train['family'] = le.fit_transform(
    train['family']
)

features.append('family')

train_sample = train.sample(
    n=50000,
    random_state=42
)

from sklearn.model_selection import train_test_split

X = train_sample[features]
y = train_sample[target]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

y_pred = model.predict(X_test)

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)

rmse = np.sqrt(
    mean_squared_error(y_test, y_pred)
)

r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))

plt.plot(
    y_test.values[:100],
    label='Actual'
)

plt.plot(
    y_pred[:100],
    label='Predicted'
)

plt.title(
    "Actual vs Predicted Sales"
)

plt.legend()

plt.show()

plt.figure(figsize=(10,5))

plt.plot(
    y_test.values[:200],
    label='Actual'
)

plt.plot(
    y_pred[:200],
    label='Predicted'
)

plt.legend()

plt.title(
    "Actual vs Predicted Sales"
)

plt.show()

importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_
})

importance.sort_values(
    by='Coefficient',
    ascending=False
)

from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(
    max_depth=10,
    random_state=42
)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

from sklearn.metrics import r2_score

print("R2 Score:", r2_score(y_test, dt_pred))